# kafka-avro-console-producer --broker-list kafka1:9092,kafka:9093 --topic test-topic --property parse.key=true --property key.separator=: --property key.schema='{"type":"string"}' --property value.schema='{"type":"record","name":"testRecord","fields":[{"name":"id","type":"long"}]}'
# kafka-avro-console-consumer --topic test-topic --bootstrap-server kafka1:9092,kafka:9093 --property parse.key=true --property key.separator=: --from-beginning

version: "3"
services:
  zookeeper1:
    container_name: zookeeper1
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      SERVERS: "zookeeper1,zookeeper2"
      MYID: "1"

  zookeeper2:
    container_name: zookeeper2
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      SERVERS: "zookeeper1,zookeeper2"
      MYID: "2"

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: "2"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181,zookeeper2:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"

  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:5.1.0
    depends_on:
      - kafka1
      - kafka2
      - zookeeper1
      - zookeeper2
    ports:
      - "8082:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper1:2181"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"